[project]
name = "spotify-songs-analysis"
version = "0.1.0"
requires-python = ">=3.14"
readme = "README.md"
authors = [
  { name = "Victor" },
  { name = "Ada" }
]

[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
